### ISSUE TITLE
Improve OpenID Connect claim matches

### ISSUE THREAD

**Issue by F1rst-Unicorn** [helfertool/helfertool#38]
I gladly noticed that the tool now supports [OpenID Connect](https://github.com/helfertool/helfertool/issues/22), thanks a lot for that!

I tried to configure our instance but unfortunately our token format is too complex for the configuration options. I have attached a sample token below. It would be great to extend support by allowing to specify a [JSONPath](https://goessner.net/articles/JsonPath/) or [JMESPath](https://jmespath.org/) to go deeper into the hierarchy. I could imagine the configuration to look like this:

```yaml
authentication:
  oidc:
    claims:
      login:
        name: $.resource_access.helfertool.roles        # JSONPath Syntax
        compare: member
        value: user
      admin:
        name: $.resource_access.helfertool.roles        # JSONPath Syntax
        compare: member
        value: admin
```

Sample Token
```json
{
  "iss": "https://myissuer.example",
  "aud": [
    "helfertool",
    "app2",
    "app3"
  ],
  "exp": 1585098334,
  "resource_access": {
    "helfertool": {
      "roles": [
        "user"
      ]
    },
    "app2": {
      "roles": [
        "admin"
      ]
    },
    "app3": {
      "roles": [
        "moderator"
      ]
    }
  },
  "scope": "openid profile email",
  "email": "user@myissuer.example",
  "given_name": "John",
  "family_name": "Doe"
}
```

**Comment by svenhertle** [comment]
Thanks for the detailed description!
I will implement one of both, probably JMESPath, but not sure for now.

**Comment by svenhertle** [comment]
Fixed in 9e5b1d4, thank you for the suggestion!

We use JMESPath now, the `name` parameter was renamed to `path`:

```
login:
    path: "resource_access.helfertool.roles"
    compare: "member"
    value: "user"
```

More complex JMESPath experessions are also possible (same meaning as before)

```
login:
    path: "contains(resource_access.helfertool.roles, 'user')"
    compare: "direct"
    value: True
```
The change is currently on the dev branch and will be part of version 1.1.0.
